source 'https://rubygems.org'

ruby    '2.3.0'

# Configuration management. keep on top of Gemfile
gem 'dotenv-rails', groups: [:development, :test]

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'rails-api'

# Use postgresql and mongo as the database for Active Record
gem 'pg'
gem 'mongoid', '~> 5.0.0'

# Use Puma as the app server
gem 'puma'

gem 'active_model_serializers'

group :development, :test do
  gem 'annotate'
  gem 'foreman'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
