source 'https://rubygems.org'

# Configuration management. keep on top of Gemfile
gem 'dotenv-rails', groups: [:development, :test]

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'rails-api'

# JSON serializer
gem 'active_model_serializers', github: 'rails-api/active_model_serializers', branch: '0-9-stable'

# Use postgresql and mongo as the database for Active Record
gem 'pg'
gem 'mongoid', '~> 5.0.0'

# Use Puma as the app server
gem 'puma'

# Authentication libraries
gem 'devise', '~> 3.5.3'
gem 'cancancan', '~> 1.10'
gem 'devise_invitable', '~> 1.5.2'
gem 'omniauth', '~> 1.3.1'
gem 'omniauth-facebook', '~> 3.0.0'

# Colored output to console
gem 'colored', '~> 1.2'

# Background jobs
gem 'sidekiq', '~> 4.0'

# Structured seed data
gem 'seedbank'

# ISO 3166 standard countries
gem 'countries', :require => 'countries/global'

# Pusher Client
gem 'pusher'

# ActiveRecord data translations
gem 'globalize', '~> 5.0.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  gem 'database_cleaner', '~> 1.5.1'
  gem 'factory_girl_rails', '~> 4.5.0'
  # Generate Fake data
  gem 'ffaker', '~> 2.0.0'
  gem 'rspec-rails',      '~> 3.3.0'
end

group :development do
  gem 'annotate', '~>2.6'
  gem 'awesome_print', '~>1.6'
  gem 'better_errors', '~>2.1'
  gem 'binding_of_caller', '~>0.7'
  gem 'foreman'
  gem 'letter_opener', '~>1.4'
  gem 'parser', '2.3.0.pre.6'
  gem 'pry-rails', '~>0.3'
  gem 'pry-byebug', '~>3.3'
  gem 'pry-doc', '~>0.8'
  gem 'quiet_assets', '~>1.1'
  gem 'rubocop', '~>0.35'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  gem 'shoulda-matchers'
  gem 'mongoid-rspec'
end

group :production do
  gem 'rails_12factor'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
