source "https://rubygems.org"
plugin "bootboot", "~> 0.2.1"

if ENV["DEPENDENCIES_NEXT"]
  ruby "3.2.2"
else
  ruby "3.0.6"
end

# Configuration management. keep on top of Gemfile
gem "dotenv-rails", groups: %i[development test]

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
if ENV["DEPENDENCIES_NEXT"]
  gem "rails", "~> 7.0.5.1"
else
  gem "rails", "~> 6.1.7.4"
end
gem "rake"

# JSON serializer
gem "active_model_serializers", "0.9.8"

# Use postgresql and mongo as the database for Active Record
if ENV["DEPENDENCIES_NEXT"]
  gem "mongoid", "8.1.1"
else
  gem "mongoid", "7.3.3"
end

gem "pg", "1.5.3"

# Use Puma as the app server
gem "puma", "5.6.4"

# Authentication libraries
gem "cancancan", "~> 3.3.0"
gem "cancancan-mongoid", "2.0.0"
if ENV["DEPENDENCIES_NEXT"]
  gem "devise", "4.9.2"
else
  gem "devise", "4.8.0"
end
gem "devise_invitable", "2.0.5"
gem "omniauth", "1.8.1"
gem "omniauth-facebook", "3.0.0"

# Colored output to console
gem "colored", "~> 1.2"

# Background jobs
gem "sidekiq", "~> 6.4"

# Structured seed data
gem "seedbank"

# ISO 3166 standard countries
gem "countries", require: "countries/global"

# Pusher Client
gem "pusher"

# ActiveRecord data translations
gem "globalize"

# Abort requests that are taking too long
gem "rack-timeout"

# wrapper for forecast.io API, Dark Sky
gem "forecast_io"

gem "geocoder"
gem "nearest_time_zone"

gem "symmetric-encryption"

gem "ruby-progressbar", require: false

gem "kaminari-actionview"
gem "kaminari-mongoid"
gem "rack-cors", "1.1.1", require: "rack/cors" # freezing to gemfile.lock version because heroku is not respecting lockfile
gem "simplecov", require: false, group: :test

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  unless ENV["DEPENDENCIES_NEXT"]
    gem "bullet"
  end
  gem "byebug"
  gem "database_cleaner"
  gem "database_cleaner-mongoid"
  gem "erb_lint", require: false
  gem "factory_bot_rails"
  # Generate Fake data
  gem "ffaker"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "standardrb"
end

group :development do
  gem "annotate"
  gem "awesome_print", "~>1.9"
  gem "better_errors", "~>2.9"
  gem "foreman", require: false
  gem "letter_opener"
end

group :test do
  gem "mongoid-rspec"
  gem "shoulda-matchers"
  gem "vcr"
  gem "webmock"
end

group :production do
  gem "rails_12factor"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "bugsnag", "~> 6.22"
Plugin.send(:load_plugin, "bootboot") if Plugin.installed?("bootboot")

if ENV["DEPENDENCIES_NEXT"]
  enable_dual_booting if Plugin.installed?("bootboot")

  # Add any gem you want here, they will be loaded only when running
  # bundler command prefixed with `DEPENDENCIES_NEXT=1`.
end
