SEED_CONDITIONS = [
  'ACL injury',
  'ADHD',
  'ARDS',
  'Abdominal aortic aneurysm',
  'Absence seizure',
  'Acanthosis nigricans',
  'Achalasia',
  'Achilles tendinitis',
  'Achilles tendon rupture',
  'Acne',
  'Acoustic neuroma',
  'Acromegaly',
  'Actinic keratosis',
  'Acute coronary syndrome',
  'Acute kidney failure',
  'Acute liver failure',
  'Acute lymphocytic leukemia',
  'Acute myelogenous leukemia (AML)',
  'Acute sinusitis',
  "Addison's disease",
  'Adenomyosis',
  'Adjustment disorders',
  'Adnexal tumors',
  'Adrenal cancer',
  'Adrenoleukodystrophy',
  'Adult ADHD',
  "Adult Still's disease",
  'Age spots (liver spots)',
  'Agoraphobia',
  'Airplane ear',
  'Albinism',
  'Alcohol intolerance',
  'Alcohol poisoning',
  'Alcoholic hepatitis',
  'Alcoholism',
  'Allergies',
  "Alzheimer's disease",
  'Ambiguous genitalia',
  'Ameloblastoma',
  'Amenorrhea',
  'Amnesia',
  'Amniotic fluid embolism',
  'Ampullary cancer',
  'Amyloidosis',
  'Amyotrophic lateral sclerosis',
  'Anal cancer',
  'Anal fissure',
  'Anal fistula',
  'Anal itching',
  'Anaphylaxis',
  'Anemia',
  'Aneurysms',
  'Angelman syndrome',
  'Angina',
  'Anhidrosis',
  'Ankylosing spondylitis',
  'Anorexia nervosa',
  'Anorgasmia',
  'Anterior prolapse (cystocele)',
  'Anthrax',
  'Antibiotic-associated diarrhea',
  'Antiphospholipid syndrome',
  'Antisocial personality disorder',
  'Anxiety',
  'Aortic aneurysm',
  'Aortic dissection',
  'Aortic valve disease',
  'Aortic valve regurgitation',
  'Aortic valve stenosis',
  'Aphasia',
  'Aplastic anemia',
  'Appendicitis',
  'Arteriosclerosis / atherosclerosis',
  'Arteriovenous fistula',
  'Arteriovenous malformation',
  'Arthritis',
  'Asbestosis',
  'Ascariasis',
  'Aspergillosis',
  'Asthma',
  'Asthma attack',
  'Astigmatism',
  'Ataxia',
  'Atelectasis',
  "Athlete's foot",
  'Atopic dermatitis (eczema)',
  'Atrial fibrillation',
  'Atrial flutter',
  'Atrial septal defect',
  'Atrioventricular canal defect',
  'Atypical depression',
  'Atypical hyperplasia of the breast',
  'Autism spectrum disorder',
  'Autoimmune hepatitis',
  'Autoimmune pancreatitis',
  'Autonomic neuropathy',
  'Avascular necrosis',
  'Baby acne',
  'Back pain',
  'Bacterial vaginosis',
  'Bad breath',
  'Bags under eyes',
  "Baker's cyst",
  'Balance problems',
  "Barrett's esophagus",
  "Bartholin's cyst",
  'Basal cell carcinoma',
  'Bed-wetting',
  'Bedbugs',
  'Bedsores (pressure sores)',
  'Bee stings',
  "Behcet's disease",
  "Bell's palsy",
  'Benign adrenal tumors',
  'Benign paroxysmal positional vertigo (BPPV)',
  'Benign peripheral nerve tumor',
  'Benign prostatic hyperplasia (BPH)',
  'Bile duct cancer',
  'Bile reflux',
  'Binge-eating disorder',
  'Bipolar disorder',
  'Bird flu (avian influenza)',
  'Black hairy tongue',
  'Bladder cancer',
  'Bladder stones',
  'Blastocystis hominis infection',
  'Blepharitis',
  'Blind loop syndrome',
  'Blocked tear duct',
  'Blood in urine (hematuria)',
  'Body dysmorphic disorder',
  'Body lice',
  'Boils and carbuncles',
  'Bone cancer',
  'Bone metastasis',
  'Bone spurs',
  'Borderline personality disorder',
  'Botulism',
  'Brachial plexus injury',
  'Bradycardia',
  'Brain AVM (arteriovenous malformation)',
  'Brain aneurysm',
  'Brain tumor',
  'Breast cancer',
  'Breast cysts',
  'Breast pain',
  'Broken ankle/broken foot',
  'Broken arm',
  'Broken collarbone',
  'Broken heart syndrome',
  'Broken leg',
  'Broken nose',
  'Broken ribs',
  'Broken toe',
  'Broken wrist/broken hand',
  'Bronchiolitis',
  'Bronchitis',
  'Brucellosis',
  'Brugada syndrome',
  'Bruxism (teeth grinding)',
  "Buerger's disease",
  'Bulimia nervosa',
  'Bullous pemphigoid',
  'Bundle branch block',
  'Bunions',
  'Burning mouth syndrome',
  'Burns',
  'Bursitis',
  'C. difficile',
  'COPD',
  'Calciphylaxis',
  'Cancer',
  'Cancer of the ureter',
  'Canker sore',
  'Carbon monoxide poisoning',
  'Carcinoid syndrome',
  'Carcinoid tumors',
  'Carcinoma of unknown primary',
  'Cardiogenic shock',
  'Cardiomyopathy',
  'Carotid artery disease',
  'Carpal tunnel syndrome',
  'Castleman disease',
  'Cataracts',
  'Cavernous malformations',
  'Cavities/tooth decay',
  'Celiac disease',
  'Cellulite',
  'Cellulitis',
  'Central nervous system vascular malformations',
  'Cerebral palsy',
  'Cervical cancer',
  'Cervical dystonia',
  'Cervical spondylosis',
  'Cervicitis',
  'Chagas disease',
  'Charcot-Marie-Tooth disease',
  'Chemo brain',
  'Chest pain',
  'Chiari malformation',
  'Chickenpox',
  'Chilblains',
  'Child abuse',
  'Childhood apraxia of speech',
  'Childhood asthma',
  'Childhood disintegrative disorder',
  'Childhood obesity',
  'Childhood schizophrenia',
  'Chlamydia',
  'Cholecystitis',
  'Cholera',
  'Cholestasis of pregnancy',
  'Chondromalacia patella',
  'Chondrosarcoma',
  'Chordoma',
  'Chronic constipation',
  'Chronic cough',
  'Chronic daily headaches',
  'Chronic exertional compartment syndrome',
  'Chronic fatigue syndrome',
  'Chronic granulomatous disease',
  'Chronic hives (urticaria)',
  'Chronic kidney disease',
  'Chronic lymphocytic leukemia',
  'Chronic myelogenous leukemia',
  'Chronic pelvic pain',
  'Chronic sinusitis',
  'Chronic traumatic encephalopathy',
  'Churg-Strauss syndrome',
  'Cirrhosis',
  'Claudication',
  'Cleft lip and cleft palate',
  'Clubfoot',
  'Cluster headache',
  'Coarctation of the aorta',
  'Cold sore',
  'Cold urticaria',
  'Colic',
  'Colon cancer',
  'Colon polyps',
  'Coma',
  'Common cold',
  'Common variable immunodeficiency',
  'Common warts',
  'Complex regional pain syndrome',
  'Complicated grief',
  'Compulsive gambling',
  'Compulsive sexual behavior',
  'Concussion',
  'Congenital adrenal hyperplasia',
  'Congenital heart defects',
  'Congenital heart disease',
  'Congenital myasthenic syndromes',
  'Congenital myopathies',
  'Conjoined twins',
  'Constipation',
  'Contact dermatitis',
  'Convergence insufficiency',
  'Conversion disorder',
  'Corns and calluses',
  'Coronary artery disease',
  'Corticobasal degeneration',
  'Costochondritis',
  'Cough headaches',
  'Cradle cap',
  'Craniopharyngioma',
  'Craniosynostosis',
  'Creutzfeldt-Jakob disease',
  "Crohn's disease",
  'Croup',
  'Cryoglobulinemia',
  'Cryptosporidium infection',
  'Cushing syndrome',
  'Cutaneous T-cell lymphoma',
  'Cyclic vomiting syndrome',
  'Cyclospora infection',
  'Cyclothymia',
  'Cystic fibrosis',
  'Cystitis',
  'Cytomegalovirus (CMV) infection',
  'Dandruff',
  "De Quervain's tenosynovitis",
  'Deep vein thrombosis',
  'Dehydration',
  'Delayed ejaculation',
  'Delayed sleep phase',
  'Delirium',
  'Dementia',
  'Dengue fever',
  'Depersonalization-derealization disorder',
  'Depression',
  'Dermatitis',
  'Dermatographia',
  'Dermatomyositis',
  'Desmoid tumors',
  'Desmoplastic tumors',
  'Deviated septum',
  'DiGeorge syndrome',
  'Diabetes',
  'Diabetes insipidus',
  'Diabetic coma',
  'Diabetic hyperosmolar syndrome',
  'Diabetic hypoglycemia',
  'Diabetic ketoacidosis',
  'Diabetic nephropathy',
  'Diabetic neuropathy',
  'Diabetic retinopathy',
  'Diaper rash',
  'Diarrhea',
  'Diffuse idiopathic skeletal hyperostosis (DISH)',
  'Dilated cardiomyopathy',
  'Diphtheria',
  'Dislocated elbow',
  'Dislocated shoulder',
  'Dislocation',
  'Dissociative disorders',
  'Diverticulitis',
  'Dizziness',
  'Double uterus',
  'Down syndrome',
  "Dressler's syndrome",
  'Drug addiction',
  'Drug allergy',
  'Dry eyes',
  'Dry mouth',
  'Dry skin',
  'Dry socket',
  'Ductal carcinoma in situ (DCIS)',
  'Dumping syndrome',
  "Dupuytren's contracture",
  'Dural arteriovenous fistulas',
  'Dust mite allergy',
  'Dwarfism',
  'Dysarthria',
  'Dyshidrosis',
  'Dyslexia',
  'Dysphagia',
  'Dysthymia',
  'Dystonia',
  'E. coli',
  'Ear infection (middle ear)',
  'Earwax blockage',
  'Eating disorders',
  'Ebola virus and Marburg virus',
  "Ebstein's anomaly",
  'Ectopic pregnancy',
  'Ectropion',
  'Edema',
  'Egg allergy',
  'Ehlers-Danlos syndrome',
  'Ehrlichiosis',
  'Eisenmenger syndrome',
  'Emphysema',
  'Encephalitis',
  'Encopresis',
  'Endocarditis',
  'Endometrial cancer',
  'Endometriosis',
  'Enlarged heart',
  'Enlarged liver',
  'Enlarged spleen',
  'Entropion',
  'Eosinophilic esophagitis',
  'Epidermoid (sebaceous) cysts',
  'Epidermolysis bullosa',
  'Epididymitis',
  'Epiglottitis',
  'Epilepsy',
  'Erectile dysfunction',
  'Esophageal cancer',
  'Esophageal spasms',
  'Esophageal varices',
  'Esophagitis',
  'Essential thrombocythemia',
  'Essential tremor',
  'Esthesioneuroblastoma',
  "Ewing's sarcoma",
  'Exercise headaches',
  'Exercise-induced asthma',
  'External compression headaches',
  'Eye floaters',
  'Eye melanoma',
  'Eyestrain',
  'Factitious disorder',
  'Factor V Leiden',
  'Familial Mediterranean fever',
  'Familial adenomatous polyposis',
  'Farsightedness',
  'Febrile seizure',
  'Fecal incontinence',
  'Fetal alcohol syndrome',
  'Fetal macrosomia',
  'Fever',
  'Fibroadenoma',
  'Fibrocystic breasts',
  'Fibromuscular dysplasia',
  'Fibromyalgia',
  'Fibrous dysplasia',
  'Flatfeet',
  'Floor of the mouth cancer',
  'Focal segmental glomerulosclerosis',
  'Folliculitis',
  'Food allergy',
  'Food poisoning',
  'Foot drop',
  'Frontal lobe seizures',
  'Frontotemporal dementia',
  'Frostbite',
  'Frozen shoulder',
  "Fuchs' dystrophy",
  'GERD',
  'Galactorrhea',
  'Gallbladder cancer',
  'Gallstones',
  'Ganglion cyst',
  'Gangrene',
  'Gas and gas pains',
  'Gastritis',
  'Gastrointestinal bleeding',
  'Gastrointestinal stromal tumors (GISTs)',
  'Gastroparesis',
  "Gaucher's disease",
  'Generalized anxiety disorder',
  'Genital herpes',
  'Genital warts',
  'Geographic tongue',
  'Germ cell tumors',
  'Gestational diabetes',
  'Giant cell arteritis',
  'Giardiasis',
  "Gilbert's syndrome",
  'Gingivitis',
  'Glaucoma',
  'Glioma',
  'Glomerulonephritis',
  'Goiter',
  "Golfer's elbow",
  'Gonorrhea',
  'Gout',
  'Grand mal seizure',
  'Granuloma annulare',
  "Graves' disease",
  'Greenstick fractures',
  'Group B strep disease',
  'Growing pains',
  'Growth plate fractures',
  'Guillain-Barre syndrome',
  'Gynecomastia',
  'H. pylori infection',
  'HIV/AIDS',
  'HPV infection',
  'Hair loss',
  'Hairy cell leukemia',
  'Hammertoe and mallet toe',
  'Hamstring injury',
  'Hand-foot-and-mouth disease',
  'Hangovers',
  'Hantavirus pulmonary syndrome',
  "Hashimoto's disease",
  'Hay fever',
  'Head and neck cancers',
  'Head lice',
  'Headaches',
  'Hearing loss',
  'Heart arrhythmias',
  'Heart attack',
  'Heart disease',
  'Heart failure',
  'Heart murmurs',
  'Heart palpitations',
  'Heart valve disease',
  'Heartburn',
  'Heat exhaustion',
  'Heat rash',
  'Heatstroke',
  'Hemangioma',
  'Hemifacial spasm',
  'Hemochromatosis',
  'Hemolytic uremic syndrome (HUS)',
  'Hemophilia',
  'Hemorrhoids',
  'Henoch-Schonlein purpura',
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis C',
  'Hepatopulmonary syndrome',
  'Hereditary hemorrhagic telangiectasia',
  'Herniated disk',
  'Hiatal hernia',
  'Hiccups',
  'Hidradenitis suppurativa',
  'High blood pressure',
  'High blood pressure (hypertension)',
  'High cholesterol',
  'Hip dysplasia',
  'Hip fracture',
  'Hip impingement',
  'Hip labral tear',
  "Hirschsprung's disease",
  'Hirsutism',
  'Histoplasmosis',
  'Hives and angioedema',
  'Hoarding disorder',
  "Hodgkin's lymphoma",
  'Horner syndrome',
  'Hot flashes',
  'Hunter syndrome',
  "Huntington's disease",
  'Hurthle cell cancer',
  'Hydrocele',
  'Hydrocephalus',
  'Hypercalcemia',
  'Hypereosinophilic syndrome',
  'Hyperglycemia in diabetes',
  'Hyperhidrosis (excessive sweating)',
  'Hyperoxaluria and oxalosis',
  'Hyperparathyroidism',
  'Hyperthyroidism',
  'Hypertrophic cardiomyopathy',
  'Hypochondria',
  'Hypoglycemia',
  'Hypogonadism',
  'Hyponatremia',
  'Hypoparathyroidism',
  'Hypopituitarism',
  'Hypoplastic left heart syndrome',
  'Hypospadias',
  'Hypothermia',
  'Hypothyroidism',
  'Ice cream headaches',
  'Ichthyosis vulgaris',
  'Idiopathic hypersomnia',
  'Idiopathic thrombocytopenic purpura (ITP)',
  "IgA nephropathy (Berger's disease)",
  'Impacted wisdom teeth',
  'Impetigo',
  'Incompetent cervix',
  'Indigestion',
  'Infant jaundice',
  'Infant reflux',
  'Infectious diseases',
  'Infertility',
  'Inflammatory bowel disease (IBD)',
  'Inflammatory breast cancer',
  'Influenza (flu)',
  'Ingrown hair',
  'Ingrown toenails',
  'Inguinal hernia',
  'Insomnia',
  'Intermittent explosive disorder',
  'Interstitial cystitis',
  'Interstitial lung disease',
  'Intestinal ischemia',
  'Intestinal obstruction',
  'Intracranial hematoma',
  'Intracranial venous malformations',
  'Intussusception',
  'Invasive lobular carcinoma',
  'Iritis',
  'Iron deficiency anemia',
  'Irritable bowel syndrome',
  'Ischemic colitis',
  'Islet cell cancer',
  'Itchy skin (pruritus)',
  'Jellyfish stings',
  'Jet lag disorder',
  'Jock itch',
  'Juvenile fibromyalgia',
  'Juvenile rheumatoid arthritis',
  'Kawasaki disease',
  'Keratitis',
  'Keratoconus',
  'Keratosis pilaris',
  'Kidney cancer',
  'Kidney cysts',
  'Kidney infection',
  'Kidney stones',
  'Kleptomania',
  'Klinefelter syndrome',
  'Klippel-Trenaunay syndrome',
  'Knee bursitis',
  'Knee pain',
  'Krabbe disease',
  'Kyphosis',
  'Lactose intolerance',
  'Laryngitis',
  'Latex allergy',
  'Lazy eye (amblyopia)',
  'Lead poisoning',
  'Left ventricular hypertrophy',
  'Legg-Calve-Perthes disease',
  "Legionnaires' disease",
  'Leukemia',
  'Leukoplakia',
  'Lewy body dementia',
  'Lice',
  'Lichen nitidus',
  'Lichen planus',
  'Lichen sclerosus',
  'Limited scleroderma (CREST syndrome)',
  'Lip cancer',
  'Lipoma',
  'Liposarcoma',
  'Listeria infection',
  'Liver cancer',
  'Liver disease',
  'Liver hemangioma',
  'Lobular carcinoma in situ (LCIS)',
  'Long QT syndrome',
  'Low blood pressure (hypotension)',
  'Low sex drive',
  'Low sperm count',
  'Lung cancer',
  'Lupus',
  'Lupus nephritis',
  'Lyme disease',
  'Lymphedema',
  'Lymphoma',
  'Lynch syndrome',
  'MRSA infection',
  "Macular degeneration,
  dry",
  "Macular degeneration,
  wet",
  'Malaria',
  'Malignant peripheral nerve sheath tumors',
  'Mammary duct ectasia',
  'Marfan syndrome',
  'Mastitis',
  'Measles',
  'Melanoma',
  'Membranous nephropathy',
  "Meniere's disease",
  'Meningioma',
  'Meningitis',
  'Menopause',
  'Menorrhagia',
  'Menstrual cramps',
  'Mental illness',
  'Meralgia paresthetica',
  'Merkel cell carcinoma',
  'Mesenteric ischemia',
  'Mesenteric lymphadenitis',
  'Mesothelioma',
  'Metabolic disorders',
  'Metabolic syndrome',
  'Metachromatic leukodystrophy',
  'Metatarsalgia',
  'Microcephaly',
  'Microscopic colitis',
  'Migraine',
  'Migraine with aura',
  'Mild cognitive impairment (MCI)',
  'Milia',
  'Milk allergy',
  'Miscarriage',
  'Mitral valve disease',
  'Mitral valve prolapse',
  'Mitral valve regurgitation',
  'Mitral valve stenosis',
  'Mittelschmerz',
  'Mixed connective tissue disease',
  'Molar pregnancy',
  'Mold allergy',
  'Moles',
  'Molluscum contagiosum',
  'Monoclonal gammopathy of undetermined significance',
  'Mononucleosis',
  'Mood disorders',
  'Morning sickness',
  'Morphea',
  "Morton's neuroma",
  'Mosquito bites',
  'Mouth cancer',
  'Movement disorders',
  'Moyamoya disease',
  "Multiple endocrine neoplasia,
  type 1 (MEN 1)",
  'Multiple myeloma',
  'Multiple sclerosis',
  'Multiple system atrophy (MSA)',
  'Mumps',
  'Muscle cramp',
  'Muscular dystrophy',
  'Myasthenia gravis',
  'Myelodysplastic syndromes',
  'Myelofibrosis',
  'Myocardial ischemia',
  'Myocarditis',
  'Myoclonus',
  'Myofascial pain syndrome',
  'Naegleria infection',
  'Nail fungus',
  'Narcissistic personality disorder',
  'Narcolepsy',
  'Nasal and paranasal tumors',
  'Nasal polyps',
  'Nasopharyngeal carcinoma',
  'Nearsightedness',
  'Neck pain',
  'Nephrogenic systemic fibrosis',
  'Nephrotic syndrome',
  'Neuroblastoma',
  'Neurodermatitis',
  'Neuroendocrine tumors',
  'Neurofibromatosis',
  'Neuromyelitis optica',
  'Nickel allergy',
  'Nicotine dependence',
  'Niemann-Pick',
  'Nightmare disorder',
  "Non-Hodgkin's lymphoma",
  'Nonalcoholic fatty liver disease',
  'Nonallergic rhinitis',
  'Nonmelanoma skin cancer',
  'Nonulcer stomach pain',
  'Noonan syndrome',
  'Norovirus infection',
  'Obesity',
  'Obsessive-compulsive disorder',
  'Occupational asthma',
  'Ocular rosacea',
  'Odontogenic lesions',
  'Oppositional defiant disorder (ODD)',
  'Optic neuritis',
  'Oral lichen planus',
  'Oral thrush',
  'Orchitis',
  'Orthostatic hypotension (postural hypotension)',
  'Osgood-Schlatter disease',
  'Osteoarthritis',
  'Osteochondritis dissecans',
  'Osteomalacia',
  'Osteomyelitis',
  'Osteoporosis',
  'Osteosarcoma',
  'Ovarian cancer',
  'Ovarian cysts',
  'Ovarian hyperstimulation syndrome',
  'Overactive bladder',
  'POEMS Syndrome',
  "Paget's disease of bone",
  "Paget's disease of the breast",
  'Painful intercourse (dyspareunia)',
  'Pancreatic cancer',
  'Pancreatic cysts',
  'Pancreatitis',
  'Panic attacks',
  'Paraneoplastic syndromes of the nervous system',
  "Parkinson's disease",
  'Parvovirus infection',
  'Patellar tendinitis',
  'Patent ductus arteriosus (PDA)',
  'Patent foramen ovale',
  'Peanut allergy',
  'Pectus carinatum',
  'Pectus excavatum',
  'Pediatric brain tumors',
  'Pediatric obstructive sleep apnea',
  'Pediatric thrombocytopenia',
  'Pediatric white blood cell disorders',
  'Pelvic inflammatory disease (PID)',
  'Pelvic organ prolapse',
  'Pemphigus',
  'Penicillin allergy',
  'Peptic ulcer',
  'Pericardial effusion',
  'Pericarditis',
  'Perimenopause',
  'Periodontitis',
  'Peripheral artery disease',
  'Peripheral nerve injuries',
  'Peripheral nerve tumors',
  'Peripheral neuropathy',
  'Peritonitis',
  'Personality disorders',
  'Pet allergy',
  "Peyronie's disease",
  'Phantom pain',
  'Phenylketonuria',
  'Pheochromocytoma',
  'Phobias',
  'Pilonidal cyst',
  'Pinched nerve',
  'Pink eye (conjunctivitis)',
  'Pinworm infection',
  'Pituitary tumors',
  'Pityriasis rosea',
  'Placenta accreta',
  'Placenta previa',
  'Placental abruption',
  'Plague',
  'Plantar fasciitis',
  'Plantar warts',
  'Pleurisy',
  'Pneumonia',
  'Pneumonitis',
  'Pneumothorax',
  'Poison ivy rash',
  'Polio',
  'Polycystic kidney disease',
  'Polycystic ovary syndrome (PCOS)',
  'Polycythemia vera',
  'Polyhydramnios',
  'Polymorphous light eruption',
  'Polymyalgia rheumatica',
  'Polymyositis',
  'Poor color vision',
  'Popliteal artery aneurysm',
  'Porphyria',
  'Post-concussion syndrome',
  'Post-polio syndrome',
  'Post-traumatic stress disorder (PTSD)',
  'Posterior cortical atrophy',
  'Posterior cruciate ligament injury',
  'Posterior prolapse (rectocele)',
  'Postherpetic neuralgia',
  'Postpartum depression',
  'Postpartum preeclampsia',
  'Postpartum thyroiditis',
  'Pouchitis',
  'Prader-Willi syndrome',
  'Precocious puberty',
  'Prediabetes',
  'Preeclampsia',
  'Prehypertension',
  'Premature birth',
  'Premature ejaculation',
  'Premature ovarian failure',
  'Premature ventricular contractions',
  'Premenstrual syndrome (PMS)',
  'Presbyopia',
  'Prescription drug abuse',
  'Preterm labor',
  'Priapism',
  'Primary aldosteronism',
  'Primary biliary cirrhosis',
  'Primary immunodeficiency',
  'Primary lateral sclerosis (PLS)',
  'Primary progressive aphasia',
  'Primary sclerosing cholangitis',
  'Proctitis',
  'Progeria',
  'Progressive supranuclear palsy',
  'Prolactinoma',
  'Prostate cancer',
  'Prostatitis',
  'Pseudogout',
  'Pseudomembranous colitis',
  'Pseudotumor cerebri',
  'Psoriasis',
  'Psoriatic arthritis',
  'Pubic lice (crabs)',
  'Pulmonary atresia',
  'Pulmonary edema',
  'Pulmonary embolism',
  'Pulmonary fibrosis',
  'Pulmonary hypertension',
  'Pulmonary valve disease',
  'Pulmonary valve stenosis',
  'Pyloric stenosis',
  'Pyoderma gangrenosum',
  'Q fever',
  'REM sleep behavior disorder',
  'Rabies',
  'Radiation enteritis',
  'Radiation sickness',
  'Ramsay Hunt syndrome',
  "Raynaud's disease",
  'Reactive arthritis',
  'Reactive attachment disorder',
  'Rebound headaches',
  'Rectal cancer',
  'Rectal prolapse',
  'Rectovaginal fistula',
  'Recurrent breast cancer',
  'Renal artery stenosis',
  'Respiratory syncytial virus (RSV)',
  'Restless legs syndrome',
  'Retinal detachment',
  'Retinal diseases',
  'Retinoblastoma',
  'Retractile testicle',
  'Retrograde ejaculation',
  'Rett syndrome',
  "Reye's syndrome",
  'Rhabdomyosarcoma',
  'Rheumatic fever',
  'Rheumatoid arthritis',
  'Rickets',
  'Ringworm (body)',
  'Ringworm (scalp)',
  'Rocky Mountain spotted fever',
  'Rosacea',
  'Roseola',
  'Rotator cuff injury',
  'Rotavirus',
  'Rubella',
  'Rumination syndrome',
  'Ruptured eardrum',
  'Ruptured spleen',
  'Sacral dimple',
  'Sacroiliitis',
  'Salivary gland cancer',
  'Salmonella infection',
  'Sarcoidosis',
  'Sarcoma',
  'Scabies',
  'Scarlet fever',
  'Schizoaffective disorder',
  'Schizoid personality disorder',
  'Schizophrenia',
  'Schizotypal personality disorder',
  'Sciatica',
  'Scleroderma',
  'Sclerosing mesenteritis',
  'Scoliosis',
  'Scorpion stings',
  'Scrotal masses',
  'Seasonal affective disorder (SAD)',
  'Seborrheic dermatitis',
  'Seborrheic keratosis',
  'Secondary hypertension',
  'Selective IgA deficiency',
  'Self-injury/cutting',
  'Separated shoulder',
  'Separation anxiety',
  'Sepsis',
  'Septic arthritis',
  'Serotonin syndrome',
  'Severe acute respiratory syndrome (SARS)',
  'Sex headaches',
  'Sexual dysfunction',
  'Sexually transmitted diseases',
  'Shaken baby syndrome',
  "Sheehan's syndrome",
  'Shellfish allergy',
  'Shigella infection',
  'Shin splints',
  'Shingles',
  'Short bowel syndrome',
  'Sick sinus syndrome',
  'Sickle cell anemia',
  'Sinus headaches',
  "Sjogren's syndrome",
  'Skin cancer',
  'Sleep apnea',
  "Sleep apnea,
  central",
  "Sleep apnea,
  obstructive",
  'Sleep disorders',
  'Sleep terrors (night terrors)',
  'Sleep-related eating disorder',
  'Sleepwalking',
  'Small bowel cancer',
  'Small bowel prolapse (enterocele)',
  'Small vessel disease',
  'Smallpox',
  'Snoring',
  'Social anxiety disorder',
  'Soft palate cancer',
  'Soft tissue sarcoma',
  'Solitary fibrous tumors',
  'Solitary rectal ulcer syndrome',
  'Sore throat',
  'Soy allergy',
  'Spermatocele',
  'Spider bites',
  'Spina bifida',
  'Spinal arteriovenous malformations',
  'Spinal cord injury',
  'Spinal cord tumor',
  'Spinal headaches',
  'Spinal stenosis',
  'Spontaneous coronary artery dissection (SCAD)',
  'Sprained ankle',
  'Sprains and strains',
  'Squamous cell carcinoma of the skin',
  'Stage 4 prostate cancer',
  'Staph infections',
  'Stevens-Johnson syndrome',
  'Stickler syndrome',
  'Stomach cancer',
  'Stomach polyps',
  'Strep throat',
  'Stress fractures',
  'Stress incontinence',
  'Stretch marks',
  'Stroke',
  'Stuttering',
  'Sty',
  'Subarachnoid hemorrhage',
  'Subconjunctival hemorrhage',
  'Sudden cardiac arrest',
  'Sudden infant death syndrome (SIDS)',
  'Suicide and suicidal thoughts',
  'Sun allergy',
  'Sunburn: Soothing solutions',
  'Suspicious breast lumps',
  'Sweating and body odor',
  "Sweet's syndrome",
  "Swimmer's ear",
  "Swimmer's itch",
  'Swine flu (H1N1 flu)',
  'Swollen lymph nodes',
  'Syphilis',
  'Syringomyelia',
  'Systemic capillary leak syndrome',
  'Systemic mastocytosis',
  'TMJ disorders',
  'Tachycardia',
  "Takayasu's arteritis",
  'Tapeworm infection',
  'Tay-Sachs disease',
  'Teen depression',
  'Temporal lobe seizure',
  'Tendinitis',
  'Tennis elbow',
  'Tension headache',
  'Testicular cancer',
  'Testicular torsion',
  'Tetanus',
  'Tetralogy of Fallot',
  'Thalassemia',
  'Thoracic aortic aneurysm',
  'Thoracic outlet syndrome',
  'Throat cancer',
  'Thrombocytopenia',
  'Thrombocytosis',
  'Thrombophlebitis',
  'Thumb arthritis',
  'Thunderclap headaches',
  'Thyroid cancer',
  'Thyroid nodules',
  'Tinea versicolor',
  'Tinnitus',
  'Toe walking',
  'Tongue cancer',
  'Tongue-tie (ankyloglossia)',
  'Tonsil cancer',
  'Tonsillitis',
  'Tooth abscess',
  'Torn meniscus',
  'Tourette syndrome',
  'Toxic hepatitis',
  'Toxic shock syndrome',
  'Toxoplasmosis',
  'Trachoma',
  'Transient global amnesia',
  'Transient ischemic attack (TIA)',
  'Transposition of the great arteries',
  'Transverse myelitis',
  'Traumatic brain injury',
  "Traveler's diarrhea",
  'Trench mouth',
  'Trichinosis',
  'Trichomoniasis',
  'Trichotillomania',
  'Tricuspid atresia',
  'Tricuspid valve disease',
  'Tricuspid valve regurgitation',
  'Trigeminal neuralgia',
  'Trigger finger',
  'Triple X syndrome',
  'Truncus arteriosus',
  'Tuberculosis',
  'Tuberous sclerosis',
  'Tularemia',
  'Turner syndrome',
  'Type 1 diabetes',
  'Type 2 diabetes',
  'Typhoid fever',
  'Ulcerative colitis',
  'Ulnar wrist pain',
  'Umbilical hernia',
  'Undescended testicle',
  'Ureteral obstruction',
  'Urethral stricture',
  'Urinary incontinence',
  'Urinary tract infection',
  'Urine color',
  'Uterine fibroids',
  'Uterine polyps',
  'Uterine prolapse',
  'Uveitis',
  'Vaginal agenesis',
  'Vaginal atrophy',
  'Vaginal cancer',
  'Vaginal dryness',
  'Vaginal fistula',
  'Vaginitis',
  'Valley fever',
  'Varicocele',
  'Varicose veins',
  'Vascular dementia',
  'Vasculitis',
  'Vasovagal syncope',
  'Ventricular fibrillation',
  'Ventricular septal defect',
  'Ventricular tachycardia',
  'Vertebral tumor',
  'Vesicoureteral reflux',
  'Viral gastroenteritis',
  'Viral hemorrhagic fevers',
  'Vitamin deficiency anemia',
  'Vitiligo',
  'Vocal cord paralysis',
  'Voice disorders',
  'Von Willebrand disease',
  'Vulvar cancer',
  'Vulvodynia',
  'Waldenstrom macroglobulinemia',
  'Water on the knee',
  "Wegener's granulomatosis",
  'West Nile virus',
  'Wheat allergy',
  'Whiplash',
  "Whipple's disease",
  'Whooping cough',
  "Wilms' tumor",
  "Wilson's disease",
  'Wolff-Parkinson-White syndrome',
  'Wrinkles',
  'Wrist pain',
  'X-linked agammaglobulinemia',
  'Yeast infection (vaginal)',
  'Yellow fever',
  'Yips',
  'Zollinger-Ellison syndrome'
]

I18n.locale = :en
SEED_CONDITIONS.each_with_index do |name, i|
  Condition.find_or_create_by!(name: name) if i % 5 == 0
end
