SEED_SYMPTOMS = [
  "Abdominal pain",
  "Absence of speech",
  "Allergy",
  "Altered mental status",
  "Anal itching",
  "Anemia",
  "Ankle pain",
  "Anxiety",
  "Aphasia",
  "Arm pain",
  "Attention deficit",
  "Back pain",
  "Bad breath",
  "Bad taste in the mouth",
  "Beau's lines",
  "Behavior disorder",
  "Bladder spasms",
  "Bleeding gums",
  "Blisters",
  "Blood in semen",
  "Blood in urine",
  "Bloody nose",
  "Bloody sputum",
  "Blunted affect",
  "Blurred vision",
  "Bowel incontinence",
  "Breast discharge",
  "Breast lumps",
  "Breast pain",
  "Brittle nails",
  "Bumps on skin",
  "Burning urination",
  "Buttock pain",
  "Catatonia",
  "Chest pain",
  "Chills",
  "Chronic pain",
  "Cloudy urine",
  "Coccydynia",
  "Cold",
  "Cold feet",
  "Cold fingers",
  "Cold hands",
  "Confusion",
  "Constipation",
  "Cough",
  "Cyanosis/turning blue",
  "Dark circles under the eyes",
  "Dark urine",
  "Decreased appetite",
  "Delirium",
  "Delusions",
  "Depigmentation of skin",
  "Depression",
  "Detrusor contraction",
  "Diarrhea",
  "Difficulty concentrating",
  "Difficulty urinating",
  "Difficulty with speech",
  "Dilated pupils",
  "Discharge from penis",
  "Distended stomach",
  "Dizziness",
  "Double vision",
  "Drainage of pus",
  "Drooling",
  "Dry eye",
  "Dry mouth",
  "Dry skin",
  "Dysarthria",
  "Dyspepsia",
  "Dysphagia",
  "Earache",
  "Easy bruising",
  "Elbow pain",
  "Emotional disorder",
  "Enlarged heart",
  "Euphoria",
  "Excessive sweating",
  "Eye discharge",
  "Eye pain",
  "Eye twitch",
  "Fainting",
  "Fatigue and tiredness",
  "Fecal incontinence",
  "Fever",
  "Finger pain",
  "Flaky scalp",
  "Flat affect",
  "Fluctuating mood",
  "Foot pain",
  "Frequent urination",
  "Gas",
  "Hair loss",
  "Hairy tongue",
  "Hallucinations",
  "Hand pain",
  "Headache",
  "Hearing loss",
  "Heartburn",
  "Heel pain",
  "Hemolysis",
  "Hemolytic anemia",
  "Hip pain",
  "Hoarseness",
  "Hot flashes",
  "Hyperactivity",
  "Hyperventilation",
  "Impotence",
  "Impulsivity",
  "Inability to regulate emotions",
  "Inattention",
  "Incontinence,
  urine",
  "Increased appetite",
  "Infertility",
  "Insomnia",
  "Itch",
  "Jaundice",
  "Jaw pain",
  "Joint cracking",
  "Joint pain",
  "Joint redness",
  "Joint stiffness",
  "Knee pain",
  "Koilonychia",
  "Labile mood",
  "Leg pain",
  "Leg sores",
  "Leg swelling",
  "Limping",
  "Loss of appetite",
  "Loss of speech",
  "Loss of taste sensation",
  "Loss of temperature sensation",
  "Low libido",
  "Low urine output",
  "Lump or mass on gums",
  "Memory loss",
  "Menstrual cramps",
  "Metallic taste in the mouth",
  "Missed menstrual period",
  "Mood swings",
  "Mouth sores",
  "Muscle cramps",
  "Muscle pain",
  "Mutism",
  "Nail clubbing",
  "Nail discoloration",
  "Nail pitting",
  "Nail separation",
  "Nasal congestion",
  "Nausea",
  "Neck pain",
  "Neglecting oneself",
  "Numbness fingers",
  "Numbness or tingling sensation in the tongue",
  "Numbness toes",
  "Onychorrhexis",
  "Overactive bladder",
  "Pain in the penis",
  "Painful gums",
  "Painful intercourse",
  "Pale skin",
  "Palpitations",
  "Paralysis",
  "Paranoia",
  "Peeling skin",
  "Pelvic pain",
  "Penile discharge",
  "Penile itching",
  "Penile pain",
  "Peripheral neuropathy",
  "Photophobia",
  "Pink eye",
  "Pleurisy",
  "Poor hygiene",
  "Proteinuria",
  "Ptosis",
  "Rash",
  "Rectal bleeding",
  "Rectal incontinence",
  "Rectal pain",
  "Red spots on the skin",
  "Red streaks on the skin",
  "Restless leg syndrome",
  "Ringing in ears",
  "Runny nose",
  "Seizures",
  "Self-neglect",
  "Shaking hands",
  "Shortness of breath",
  "Shoulder pain",
  "Snoring",
  "Sore throat",
  "Sore tongue",
  "Stiff neck",
  "Stomach cramps",
  "Stool color & texture changes",
  "Strange behavior",
  "Suicide",
  "Swollen ankles and/or swollen feet",
  "Swollen eyes",
  "Swollen joints",
  "Swollen lip",
  "Swollen lymph nodes",
  "Swollen testicles",
  "Swollen tongue",
  "Swollen tonsils",
  "Tachycardia",
  "Testicular pain",
  "Thirst",
  "Tingling in hands and feet",
  "Toe pain",
  "Toothache",
  "Tremor",
  "Tunnel vision",
  "Unsteady gait",
  "Unusual behavior",
  "Urge incontinence",
  "Urinary retention",
  "Urinary urgency",
  "Urine odor",
  "Vaginal bleeding",
  "Vaginal discharge",
  "Vaginal dryness",
  "Vaginal itching",
  "Vaginal odor",
  "Vaginal pain",
  "Vertical ridges on the fingernails",
  "Vertigo",
  "Vision loss",
  "Vocal outbursts",
  "Vomiting",
  "Vomiting blood",
  "Watery eye",
  "Weakness",
  "Weight gain",
  "Weight loss",
  "Wheezing",
  "White tongue",
  "Wrist pain"
]

I18n.locale = :en
SEED_SYMPTOMS.each_with_index do |name, i|
  Symptom.find_or_create_by!(id: i+1).update_attributes!(name: name)
end
